"use client";

import { useImpulseStore } from "@/app/hooks/useImpulseStore";
import { AlertTriangle, Scissors } from "lucide-react";

interface ReceiptItem {
    label: string;
    cost: string;
}

export interface RoastReceiptProps {
    productName: string;
    items: ReceiptItem[];
    total: string;
    roast: string;
}

export function RoastReceipt({ productName, items, total, roast }: RoastReceiptProps) {
    const { startFuneral } = useImpulseStore();

    const handleFuneral = () => {
        // Convert generic receipt data into our Store format
        startFuneral({
            title: productName,
            price: { value: total.replace(/[^0-9.]/g, ""), currency: "USD" },
            image: { imageUrl: "https://placehold.co/400x400/000000/FFF?text=Receipt" },
            itemWebUrl: "#"
        });
        setTimeout(() => window.location.reload(), 100);
    };

    return (
        <div className="my-6 mx-auto w-full max-w-sm animate-in slide-in-from-bottom-4 duration-500">
            {/* Receipt Paper Effect */}
            <div className="bg-white text-black font-mono p-6 shadow-2xl relative">

                {/* Jagged Top */}
                <div className="absolute top-0 left-0 right-0 h-4 -mt-4 bg-white [mask-image:linear-gradient(to_bottom,transparent,black)]"
                    style={{ clipPath: "polygon(0% 100%, 5% 0%, 10% 100%, 15% 0%, 20% 100%, 25% 0%, 30% 100%, 35% 0%, 40% 100%, 45% 0%, 50% 100%, 55% 0%, 60% 100%, 65% 0%, 70% 100%, 75% 0%, 80% 100%, 85% 0%, 90% 100%, 95% 0%, 100% 100%)" }}>
                </div>

                {/* Header */}
                <div className="text-center border-b-2 border-dashed border-black/20 pb-4 mb-4">
                    <h2 className="text-xl font-bold uppercase tracking-widest">WalletWake Inc.</h2>
                    <p className="text-xs text-zinc-500">Official Bill of Bad Decisions</p>
                    <p className="text-xs mt-1">{new Date().toLocaleDateString()} {new Date().toLocaleTimeString()}</p>
                </div>

                {/* Dynamic Line Items (Generated by AI) */}
                <div className="space-y-2 text-sm mb-4">
                    {items.map((item, i) => (
                        <div key={i} className="flex justify-between">
                            <span>{item.label}</span>
                            <span className="font-bold">{item.cost}</span>
                        </div>
                    ))}
                </div>

                {/* Total */}
                <div className="border-t-2 border-black border-b-2 py-2 mb-4 flex justify-between text-lg font-bold">
                    <span>TOTAL LOSS</span>
                    <span>{total}</span>
                </div>

                {/* The Roast */}
                <div className="text-center text-xs italic mb-6 px-4">
                    "{roast}"
                </div>

                {/* Barcode / Footer */}
                <div className="flex flex-col items-center gap-2 opacity-50">
                    <div className="h-8 w-full bg-repeat-x" style={{ backgroundImage: "linear-gradient(90deg, #000 50%, transparent 50%)", backgroundSize: "4px 100%" }}></div>
                    <p className="text-[10px] uppercase">No Refunds on Dignity</p>
                </div>

                {/* Action Button */}
                <button
                    onClick={handleFuneral}
                    className="mt-6 w-full bg-black text-white py-3 text-xs font-bold uppercase tracking-widest hover:bg-red-600 transition-colors flex items-center justify-center gap-2"
                >
                    <Scissors className="w-4 h-4" />
                    Accept Fate (Funeral)
                </button>

                {/* Jagged Bottom */}
                <div className="absolute bottom-0 left-0 right-0 h-4 -mb-4 bg-white"
                    style={{ clipPath: "polygon(0% 0%, 5% 100%, 10% 0%, 15% 100%, 20% 0%, 25% 100%, 30% 0%, 35% 100%, 40% 0%, 45% 100%, 50% 0%, 55% 100%, 60% 0%, 65% 100%, 70% 0%, 75% 100%, 80% 0%, 85% 100%, 90% 0%, 95% 100%, 100% 0%)" }}>
                </div>
            </div>
        </div>
    );
}